-- MAIN 테이블 생성

CREATE TABLE CORP_INFO_MAIN (
  KED_CODE    VARCHAR(10)  
 ,CORP_NO     VARCHAR(20)  
 ,AREA_NM     VARCHAR(20)  
 ,BASE_NM     VARCHAR(20)
 ,ZIP_CODE    VARCHAR(20)
 ,ADDRESS_1   VARCHAR(200)
 ,ADDRESS_2   VARCHAR(200)
 ,ADDRESS_A   VARCHAR(300)
 ,CORP_NM     VARCHAR(50)
 ,EMP_CNT     INT
 ,TOTAL_SALES BIGINT
 ,KS_CATE_1   VARCHAR(20)
 ,KS_CATE_2   VARCHAR(20)
 ,MID_CODE_YN VARCHAR(20)
 ,PRIMARY KEY (KED_CODE)
)