DROP TABLE IF EXISTS KED5031_H;

CREATE TABLE KED5031_H (
    KEDCD    VARCHAR(10)   NOT NULL COMMENT '기업식별ID',
    STD_DT   CHAR(8)       NOT NULL COMMENT '최종 입력된 정보의 기준일자(YYYYMMDD)',
    OPNN_CCD CHAR(2)       NOT NULL COMMENT '종합의견 구분코드(코드클래스:0046)',
    CTT      VARCHAR(3000) NULL     COMMENT '종합의견내용',

    UPDATED   VARCHAR(20)   COMMENT '갱신일',

    PRIMARY KEY (KEDCD, STD_DT, OPNN_CCD)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='KED5031_H 종합의견 이력';
