-- 특허및실용신안기업-요약
CREATE TABLE KED50TG (
  BASE_DT	      VARCHAR(8)
 ,BZNO	        VARCHAR(10)
 ,CONO	        VARCHAR(13)
 ,PND_PTNTR_CN	BIGINT
 ,PND_UM_CN	    BIGINT
 ,REG_PTNTR_CN	BIGINT
 ,REG_UM_CN	    BIGINT
 ,REG_VLD_PTNTR_CN	BIGINT
 ,REG_VLD_UM_CN	BIGINT
 ,KODATA_UPD_DT	VARCHAR(8)
 ,CONO_BAD_INFO	VARCHAR(2)
 ,BZNO_BAD_INFO	VARCHAR(2)
 ,CO_REG_INFO	VARCHAR(2)
 ,LQDT_INFO	    VARCHAR(2)
 ,KODATACD	    VARCHAR(10)
 ,KODATA_ENP_NM	VARCHAR(100)
 ,KODATA_REPER_NM	VARCHAR(50)
 ,LOC	VARCHAR(6)
 ,ADDR1	VARCHAR(200)
 ,ADDR2	VARCHAR(200)
 ,TEL_NO	VARCHAR(20)
 ,ESTB_DT	VARCHAR(8)
 ,ASET_T_SUM	BIGINT
 ,LIAB_T_SUM	BIGINT
 ,SAM	BIGINT
 ,BZPF	BIGINT
 ,NPFCT	BIGINT
 ,RND_MP	BIGINT
 ,ACCT_DT	VARCHAR(8)
 ,BZC_CD	VARCHAR(6)
 ,PRIMARY KEY(KODATACD, BASE_DT)
);	
