-- 재무제표 이력
CREATE TABLE KED5003_H (
  KEDCD	      VARCHAR(10)
 ,IN_DATE     CHAR(8)
 ,ACCT_DT	    VARCHAR(8)
 ,SUMASSET	  BIGINT
 ,PAYMENTFUND BIGINT
 ,FUNDTOTAL	  BIGINT
 ,SALES	      BIGINT
 ,PROFIT	    BIGINT
 ,TERMNETPROFIT BIGINT
 ,PRIMARY KEY (KEDCD, IN_DATE)
);