-- 재무제표
CREATE TABLE KED5003 (
  KEDCD	        VARCHAR(10)
 ,ACCT_DT	      VARCHAR(8)
 ,SUMASSET	    BIGINT
 ,PAYMENTFUND   BIGINT
 ,FUNDTOTAL	    BIGINT
 ,SALES	        BIGINT
 ,PROFIT	      BIGINT
 ,TERMNETPROFIT BIGINT
 ,PRIMARY KEY (KEDCD, ACCT_DT)
);